---

- name: ensure tasks run only on selected os releases
  block:

    - name: adding this block for idempotency as the '@GNOME' group seems to vanish upon installation
      block:

        - name: install gnome desktop
          ansible.builtin.package:
            name:
              - "@GNOME"
              - "{{ linux_station.packages.gnome.install }}"
            state: latest

      rescue:

        - name: do not install '@GNOME'
          ansible.builtin.package:
            name: "{{ linux_station.packages.gnome.install }}"
            state: latest

    - name: get the default systemd target
      ansible.builtin.command:
        cmd: systemctl get-default
      changed_when: false
      register: cmd_systemd_target

    - name: set system to boot into graphical mode
      ansible.builtin.command:
        cmd: "systemctl set-default graphical.target"
      when: cmd_systemd_target.stdout != "graphical.target"

  when: >
    ansible_distribution == "CentOS" or
    ansible_distribution == "Fedora" or
    ansible_distribution == "RedHat" or
    ansible_distribution == "Rocky"

...
