---

- name: ensure tasks run only on selected os releases
  block:

    - name: enable rpfusion repositories
      ansible.builtin.include_role:
        name: repo__rpm_fusion

    - name: install steam
      ansible.builtin.package:
        name:
          - steam
          - dbus-x11
        state: latest

    - name: create steam user
      ansible.builtin.user:
        name: steam
        home: /home/steam
        groups: games,audio

    - name: ensure /home/steam is owned by steam in case it is a mountpoint
      ansible.builtin.file:
        path: /home/steam
        recurse: true
        owner: steam
        group: steam

    # xbox dongle driver for linux
    - name: install xone driver dependencies
      ansible.builtin.package:
        name:
          - cabextract
          - curl
          - dkms
          - git-core
          - kernel
          - kernel-headers
        state: latest

    - name: initialize xone local directory
      ansible.builtin.file:
        path: /opt/xone
        state: absent

    - name: clone xone repository
      ansible.builtin.command:
        cmd: git clone https://github.com/medusalix/xone
        chdir: /opt

    - name: provide an error handler if the xone driver is already installed
      block:

        - name: install xone driver
          ansible.builtin.command:
            cmd: ./install.sh --release
            chdir: /opt/xone
          register: cmd_xone_install

      rescue:

        - name: uninstall existing xone driver
          ansible.builtin.command:
            cmd: ./uninstall.sh
            chdir: /opt/xone
          when:
            - cmd_xone_install is failed
            - "'already installed' in cmd_xone_install.stderr"

        - name: reinstall xone driver
          ansible.builtin.command:
            cmd: ./install.sh --release
            chdir: /opt/xone

    - name: download dongle firmware
      ansible.builtin.command:
        cmd: xone-get-firmware.sh --skip-disclaimer

    - name: below are some hacky procedures for pipewire audio sharing accross multiple users
      ansible.builtin.debug:
        msg: users that will share the pipewire-pulse socket must be members of the audio group
      delegate_to: localhost
      run_once: true

    - name: remove default pipewire-pulse socket
      ansible.builtin.lineinfile:
        path: /usr/lib/systemd/user/pipewire-pulse.socket
        regexp: '^.*ListenStream=%t/pulse/native'
        state: absent

    - name: create custom pipewire-pulse socket
      ansible.builtin.blockinfile:
        path: /usr/lib/systemd/user/pipewire-pulse.socket
        marker: "##### {mark} custom pipewire-pulse socket #####"
        insertafter: "\\[Socket\\]"
        block: |
          ExecStartPre=rm -f /tmp/pulse-socket
          ExecStopPost=rm -f /tmp/pulse-socket
          ListenStream=/tmp/pulse-socket
          SocketGroup=audio
          SocketMode=0660

    - name: create global pipewire config directory
      ansible.builtin.file:
        path: /etc/pipewire
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: create default pipewire-pulse configuration
      ansible.builtin.command:
        cmd: cp /usr/share/pipewire/pipewire-pulse.conf /etc/pipewire/.

    - name: update socket in pipewire-pulse configuration
      ansible.builtin.command:
        cmd: sed -i -e 's|#"unix:/tmp/something"|"unix:/tmp/pulse-socket"|' /etc/pipewire/pipewire-pulse.conf

    - name: set PULSE_SERVER environment variable
      ansible.builtin.copy:
        dest: /etc/profile.d/pipewire-pulse.sh
        content: "export PULSE_SERVER=/tmp/pulse-socket"

    - name: create sudoers file to run steam
      ansible.builtin.copy:
        dest: /etc/sudoers.d/steam
        content: "%games ALL=(steam) NOPASSWD:SETENV: /usr/bin/steam"

    - name: how to run steam as a different user
      ansible.builtin.debug:
        msg: |
          1. sudo usermod -aG games,audio <your_user_name>
          2. you may need to login again for the first item to take effect
          3. xhost +; sudo -u steam PULSE_SERVER=/tmp/pulse-socket XDG_RUNTIME_DIR=/tmp/steam steam

  when: ansible_distribution == "Fedora"

...
